// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateCustomerInput struct {
	Name        string   `json:"name"`
	Groups      []string `json:"groups"`
	LastPayment string   `json:"lastPayment"`
	NextPayment string   `json:"nextPayment"`
}

type CreateGroupInput struct {
	Name       string             `json:"name"`
	Instructor string             `json:"instructor"`
	Times      []*CreateTimeInput `json:"times"`
}

type CreateInstructorInput struct {
	Name string `json:"name"`
}

type CreateOrganizationInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreatePaymentInput struct {
	Amount     float64 `json:"amount"`
	Date       string  `json:"date"`
	GroupID    string  `json:"groupId"`
	CustomerID string  `json:"customerId"`
}

type CreateTimeInput struct {
	Day        string `json:"day"`
	StartHour  string `json:"start_hour"`
	FinishHour string `json:"finish_hour"`
}

type Customer struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Groups      []*Group `json:"groups"`
	LastPayment string   `json:"lastPayment"`
	NextPayment string   `json:"nextPayment"`
}

type Group struct {
	ID         string      `json:"id"`
	Name       string      `json:"name"`
	Instructor *Instructor `json:"instructor"`
	Times      []*Time     `json:"times"`
}

type Instructor struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	OrganizationID string `json:"organizationId"`
}

type Organization struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Payment struct {
	ID           string        `json:"id"`
	Amount       float64       `json:"amount"`
	Date         string        `json:"date"`
	Customer     *Customer     `json:"customer"`
	Organization *Organization `json:"organization"`
	Group        *Group        `json:"group"`
}

type Time struct {
	ID         string `json:"id"`
	GroupID    string `json:"groupId"`
	Day        string `json:"day"`
	StartHour  string `json:"start_hour"`
	FinishHour string `json:"finish_hour"`
}

type TokenResponse struct {
	AccessToken string `json:"accessToken"`
}

type UpdateCustomerInput struct {
	Name        *string   `json:"name,omitempty"`
	Groups      []*string `json:"groups,omitempty"`
	LastPayment *string   `json:"lastPayment,omitempty"`
	NextPayment *string   `json:"nextPayment,omitempty"`
}

type UpdateGroupInput struct {
	Name       *string            `json:"name,omitempty"`
	Instructor *string            `json:"instructor,omitempty"`
	Times      []*UpdateTimeInput `json:"times,omitempty"`
}

type UpdateInstructorInput struct {
	Name *string `json:"name,omitempty"`
}

type UpdateOrganizationInput struct {
	Name     *string `json:"name,omitempty"`
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

type UpdatePaymentInput struct {
	Amount     *float64 `json:"amount,omitempty"`
	Date       *string  `json:"date,omitempty"`
	GroupID    *string  `json:"groupId,omitempty"`
	CustomerID *string  `json:"customerId,omitempty"`
}

type UpdateTimeInput struct {
	ID         string  `json:"id"`
	Day        *string `json:"day,omitempty"`
	StartHour  *string `json:"start_hour,omitempty"`
	FinishHour *string `json:"finish_hour,omitempty"`
}
